name: Haskell CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache haskell
        uses: actions/cache@v3.3.2
        with:
          path: |
            ~/.ghc
          key: ${{ runner.os }}-ghc-${{ hashFiles('**/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-ghc-

      - name: Cache Stack build artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Setup Haskell
        uses: haskell-actions/setup@v2.6.0
        with:
          ghc-version: '9.4.8'
          enable-stack: true
          stack-version: 'latest'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev

      - name: Build binary
        run: make

      - name: Run tests
        run: make test

  # push:
  #   runs-on: ubuntu-latest
  #   needs: [build-and-test]
  #   env:
  #     MIRROR_URL: "git@github.com:EpitechPromo2026/B-FUN-500-PAR-5-2-glados-stanislas.commenge.git"
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0
  #   - uses: pixta-dev/repository-mirroring-action@v1
  #     with:
  #       target_repo_url: ${{ env.MIRROR_URL }}
  #       ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
