name: Haskell CI

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
      - 0-dev

jobs:
  test_on_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '8.8.4'
          enable-stack: true
          stack-version: 'latest'

      - name: Install project dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgmp-dev
          stack init
          stack setup
          stack install

      - name: Run "make test" for Haskell
        working-directory: ${{ github.workspace }}
        run: make test

      - name: Create a Release in a GitHub Action
        uses: comnoco/create-release-action@v2.0.5
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

            